### ISSUE TITLE
Bankverbindung

### ISSUE THREAD

**Issue by kathse-net** [Westwoodlabs/Mitgliedsantrag#1]

**Comment by psteffen** [comment]
Grundsätzlich wollen wir eigentlich keine Überweisung offensiv als Zahlart anbieten. Ich wüde daher eigentlich sogar soweit gehen und die Auswahl von Antrag entfernen. Überweisung ist für uns eher nervig in der Buchung. 

Man kann das ja weiter anbieten, aber nicht so offensiv. Ich würde es daher eher vom Antrag entfernen.

**Comment by twiddau** [comment]
@psteffen Sehe ich ein wenig anders, der Aufwand einer Überweisung gegenüber Lastschrift unterscheidet sich nicht signifikant. 

Bei Lastschrift haben wir im Entropia bspw. sogar die Herausforderung, dass die Bank (Spk Karlsruhe) uns das als einzelne Sammelgutschrift gutschreibt (die Du dann auf alle Mitgliedkonten mit Lastschrift aufsplitten musst) und dann alles was geplatzt ist wieder einzeln wegbucht (die Du dann wieder dem Mitgliedskonto zuordnen musst). Vielleicht ist das zumindest bei der neuen Bank der WWLabs anders. :-)

Bei einer Überweisung musst Du die Überweisung zwar zuordnen, aber mit einem passenden Verwendungszweck lässt sich das wunderbar weg automatisieren.

**Comment by psteffen** [comment]
Zumindest hatten wir das mal so besprochen, dann muss man auch niemanden an seine Zahlungen erinnern :D

Solange eine Überweisung ankommt, gebe ich dir Recht, ist sie einfacher.

**Comment by twiddau** [comment]
Klar, das mit den Zahlungen erinnern ist ein Argument, allerdings ein "Mahnwesen" wirst Du für alle Zahlungsmittel benötigen. :-) Ich kann aber auch nachvollziehen warum Leute lieber überweisen (oder sogar bar zahlen) möchten.

**Comment by psteffen** [comment]
Sag ja nicht, dass wir nichts anderes Anbieten wollen, nur die frage ist wie offensiv wir das tun :) 

Rücklastschriften sollten ja hoffentlich eher die seltenheit sein.

**Comment by foorschtbar** [comment]
Ich persönlich würde die Überweisungsoption auch drinnen lassen, aber vlt. die Reihenfolge ändern und als zweite Option dann mit dem Text `Ich überweise den Betrag zum 1. jeden Monats`

+ Bankverbindung dann in die Fußzeile

**Comment by psteffen** [comment]
Würde das Issue dann erst mal auf lassen, bis die BV vorliegt (also die offizielle).

**Comment by psteffen** [comment]
Closed with 2277ffb
