### ISSUE TITLE
Datenschutzhinweise

### ISSUE THREAD

**Issue by psteffen** [Westwoodlabs/Mitgliedsantrag#2]
Fehlen aktuell komplett.

**Comment by foorschtbar** [comment]
*hust*

Text reicht, ich würde den dann einbauen :)

**Comment by foorschtbar** [comment]
So oder so ähnlich: 

Der Verein Westwoodlabs e.V. als verantwortliche Stelle nutzt und verarbeitet die in dieser Beitrittserklärung erhobenen personenbezogenen Daten. Vor- und Nachname, Geburtsdatum, Anschrift, E-Mail-Adresse, Mitgliedsbeitrag, Art der Mitgliedschaft sowie Bankverbindung werden zum Zweck der Vereins- und Mitgliederverwaltung, beispielsweise für die Übermittlung von Vereinsinformationen durch den Verein oder für den Einzug von Mitgliedsbeiträgen verarbeitet. Eine Übermittlung an Dritte oder eine Datennutzung zu Werbezwecken findet nicht statt. Name, Vorname, E-Mail-Adresse und ggf. Pseudonym (Nickname) werden zudem zum Zweck der vereinsinternen Kommunikation per Mailingliste genutzt und verarbeitet und können von allen Mitgliedern der Mailingliste eingesehen werden. Jede Person hat das Recht auf Auskunft, Berichtigung, Löschung, und Einschränkung der Verarbeitung seiner gespeicherten personenbezogenen Daten. Bei Beendigung der Mitgliedschaft werden die zum Zweck der Vereins- und Mitgliederversammlung gespeicherten personenbezogenen Daten mit Ablauf der gesetzlich vorgeschriebenen Aufbewahrungsfrist gelöscht.
