### ISSUE TITLE
Mandatesreferenz im PDF?

### ISSUE THREAD

**Issue by psteffen** [Westwoodlabs/Mitgliedsantrag#3]
Die Mandatesreferenz sollte ja für jedes Mandat individuell sein. Eventuell macht ein Hinweis, dass die dann mitgeteilt wird mehr Sinn.

**Comment by foorschtbar** [comment]
`Mandatsreferenz: Wird individuell mitgeteilt.` oder komplett entfernen? Ich weiß nicht welche vorgaben es für so ein SEPA-Lastschriftmandat gibt...

**Comment by psteffen** [comment]
Finde den Vorschlag gut. Also mitteilen.
