### ISSUE TITLE
Streichung "freiwilliger Beitrag"

### ISSUE THREAD

**Issue by psteffen** [Westwoodlabs/Mitgliedsantrag#7]
Ein freiwilliger Mitgliedsbeitrag ist keiner mehr sobald er freiwillig ist. Dann ist es eine Spende. Steuerrechtlich ein unterschied (obgleich man bei uns beides mit einer Spendenbescheinigung belegen darf). Würde daher eher auf das Layout des alten Antrags setzen (auswahl der Mitgliedschaft und Freifeld für den Beitrag)

**Comment by psteffen** [comment]
Passt zu #5

**Comment by foorschtbar** [comment]
Idee war das nicht "mindestens" und dann als Freitext sondern Erstmal die grundsätzliche Einstufung und wer möchte kann den Betrag zum einen "Zusatzbeitrag" erhöhen. Das Wording kann man da sicherlich noch verbessern.

**Comment by psteffen** [comment]
Ja das fand ich auf dem alten Antrag ganz gut gelöst. Wenn man eh was Eintragen muss ist die Schwelle zu "ich trage mehr ein" geringer als wenn ich das zusätzlich tun muss. Finde das "aufteilen" so auch eher verwirrend.
